### ISSUE TITLE
1.2.141.1 is out of date (already!)

### ISSUE THREAD

**Issue by expipiplus1** [apenngrace/homebrew-vulkan#10]
1.2.141.2 was released yesterday.

I wonder how easy it would be to get this updating automatically?

**Comment by apenngrace** [comment]
I update when I get emails from LunarG.  Let me know if you have suggestions.  Most of the time I just update versions and hashes, but sometimes I need to debug the cask script.

**Comment by apenngrace** [comment]
It's now updated.

**Comment by expipiplus1** [comment]
Thanks!

Emails are probably good, I guess I was just unlucky trying to use things in the window between lunarg deleting the tarball and this repo being updated.

Would be nice if they didn't delete the tarballs for old versions though...

**Comment by apenngrace** [comment]
Yeah... that’s annoying. Btw, they changed from tarball to dmg, which made me have to debug the script.

**Comment by expipiplus1** [comment]
thanks for keeping this repo going!
