### ISSUE TITLE
missing spirv-cross

### ISSUE THREAD

**Issue by expipiplus1** [apenngrace/homebrew-vulkan#12]
Hi,

Often when using homebrew-vulkan I get an error message on installation about missing spirv-cross

```
==> Tapping apenngrace/vulkan
Cloning into '/usr/local/Homebrew/Library/Taps/apenngrace/homebrew-vulkan'...
Tapped 1 cask (29 files, 36.2KB).
==> Caveats
Installing vulkan-sdk means you have AGREED to the license at:
  https://vulkan.lunarg.com/sdk/home#sdk-license

==> Downloading https://sdk.lunarg.com/sdk/download/1.2.148.0/mac/vulkansdk-macos-1.2.148.0.dmg?Human=true
==> Verifying SHA-256 checksum for Cask 'vulkan-sdk'.
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Installing Cask vulkan-sdk
ditto: WARNING: bom /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/20200827-1934-vv2vlf.bom contains no files, nothing copied
Error: It seems the symlink source '/usr/local/Caskroom/vulkan-sdk/1.2.148.0/macOS/bin/spirv-cross' is not there.
==> Purging files for version 1.2.148.0 of Cask vulkan-sdk
```

I'm running 

```
        brew tap apenngrace/homebrew-vulkan 
        brew cask install vulkan-sdk
```

I don't have Mac for development and this is all happening on a github runner (https://github.com/expipiplus1/vulkan/pull/154/checks?check_run_id=1037004886)

Let me know if there's anymore info I can provide

**Comment by apenngrace** [comment]
Sorry, I'm not familiar with the Github runner environment.

To get more insight on what's happen, you can change the command to: `brew cask install vulkan-sdk --verbose`.

When I run my script on my laptop, homebrew does a lot of automatic actions when it downloads and extracts files from a `dmg` file.  

Here are the automatic actions I see it do:
- Downloads the dmg file.
- `hdiutil attach`
- `mkbom`
- `ditto`
- `diskutil eject`
- `cp -pR` for all files in the top level directory copied from the dmg into the target directory `/usr/local/Caskroom/vulkan-sdk/[version number]/`

After that is when brew resumes my script executing at line 13.  In your output, it looks like `ditto` gives a warning that no files were copied.  So, there is something happening between downloading the file and when `ditto` runs.  Seeing the verbose output will hopefully give you more hints on the problem.

**Comment by expipiplus1** [comment]
`--verbose` fixed it ;) https://github.com/expipiplus1/vulkan/pull/144/checks?check_run_id=1039503262

I'll update once it fails again, I'm pretty sure it's nondeterministic

**Comment by expipiplus1** [comment]
Hmm, still seems to happen now and then









https://github.com/expipiplus1/vulkan/pull/194/checks?check_run_id=1345612568#step:8:32

**Comment by apenngrace** [comment]
Sorry, I don’t have an answer for you on this.  

It looks like you would need to really debug homebrew code.  As I mentioned above, homebrew takes a number of automated actions when it runs a script.  My best guess is that for some reason files are not getting properly extracted or copied in your environment, since ditto has a warning about there not being any files.

If you find a solution then send a pull request.

Good Luck!

**Comment by expipiplus1** [comment]
sure, no worries, not expecting a magic solution here :)

I've set it to retry the install step twice, hopefully that's an improvement.
