### ISSUE TITLE
Vulkan SDK 1.1.121.0 link no longer exists

### ISSUE THREAD

**Issue by klingerj** [apenngrace/homebrew-vulkan#6]
Hi there,

Just want to say that I appreciate that this cask exists. I use it with Travis CI for one of my own hobby projects.

I don't know if you still actively maintain this, but it looks like something similar happened as in #3. Vulkan SDK version from 1.1.121.0 is no longer available and has been replaced with 1.1.121.1. If you could change the SDK version in the script to use 1.1.121.1, or perhaps an older version that is unlikely to change, that would be amazing. Thank you!

Joe

**Comment by apenngrace** [comment]
Thanks for letting me know about the problem.  Typically LunarG sends an email about Vulkan SDK updates, but they didn't send one out for this point update for whatever reason.  The last email I got was on September 12, 2019 about 1.1.121.0.  I usually go by that as to when I update cask script.

I updated the script to 1.1.121.1 a few minutes ago.  As to which version is unlikely to change, I have no idea.  I'm curious if homebrew has a way to install a specific cask version by url for example.  If you discover such a feature, let me know.

If you have any hobby projects that I can check out, I'd be curious to see them.  I created this cask just to make it easier to install the sdk and play with it.
